### ISSUE TITLE
Fish shell delay

### ISSUE THREAD

**Issue by krzkrzkrz** [edc/bass#10]
In `~/.config/fish/config.fish`, I have:

    bass source ~/.nvm/nvm.sh ';' nvm use 0.12.2

Every time a new Fish shell terminal is opened. It takes almost a second for the shell to load. Without this line, the Fish shell loads fast.

Any pointers?

**Comment by edc** [comment]
I see you commented in the linked issue. Does switching to n solve the problem? Is this good to close?

**Comment by krzkrzkrz** [comment]
Yeap `n` does make things much faster. Closing for now
