### ISSUE TITLE
bass: fish: Unknown command 'source'

### ISSUE THREAD

**Issue by mgadda** [edc/bass#11]
I installed bass per the instructions in [README.md](https://github.com/edc/bass/blob/master/README.md). I ran the example:

```fish
> bass export X=3
fish: Unknown command 'source'
/Users/mgadda/.config/fish/functions/bass.fish (line 13):     source $__script
                                                              ^
in function 'bass',
	called on standard input,
	with parameter list 'export X=3'
```

According to the fish documentation, there is no `source` command, only `.`. When I updated `~/.config/fish/functions/bass.fish` and replaced the reference to `source` with `.` the example succeeded.

**Comment by edc** [comment]
Interesting. There is a source command: http://fishshell.com/docs/current/commands.html#source. What version of fish do you use?

**Comment by edc** [comment]
The document actually states `.` will be deprecated:

> . (a single period) is an alias for the source command. The use of . is deprecated in favour of source, and . will be removed in a future version of fish.

**Comment by edc** [comment]
OK. I found the commit: https://github.com/fish-shell/fish-shell/commit/5818289c2da8e53b8b52b69064254576ba7d839a. So apparently you need fish version 2.1.0 or higher. Are you able to upgrade fish?

**Comment by mgadda** [comment]
Oh my apologies. I can certainly update.
