### ISSUE TITLE
%WSLENV%: invalid variable name

### ISSUE THREAD

**Issue by daniel-shuy** [edc/bass#110]
When using `bass` in WSL, the command works, but an error is displayed:
```
set: %WSLENV%: invalid variable name. See `help identifiers`
```

From debugging with `-d`, the temp script file generated by `__bass.py` contains:
```
set -g -x %WSLENV% ""
```

**Comment by edc** [comment]
Can you test the fix and let me know if it works?

**Comment by daniel-shuy** [comment]
It worked, thanks for the quick fix!

This was due to configuring WSL to use GCM (git-credential-manager) for Windows without installing Git for Windows (https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/wsl.md#configuring-wsl-without-git-for-windows).
