### ISSUE TITLE
Weird bash error after installing via fundle

### ISSUE THREAD

**Issue by philbooth** [edc/bass#24]
```
~ $ fundle -v
0.4.0
~ $ fundle plugin 'edc/bass'
~ $ fundle install
Installing edc/bass
~ $ fundle init
~ $ bass
test: Missing argument at index 2
bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `; echo "-__-__-__bass___-env-output-__bass_-__-__-__-__"; python -c 'import os,json; print(json.dumps({k:v for k,v in os.environ.items()}))''
Command '['bash', '-c', '; echo "-__-__-__bass___-env-output-__bass_-__-__-__-__"; python -c \'import os,json; print(json.dumps({k:v for k,v in os.environ.items()}))\'']' returned non-zero exit status 2
Bass encountered an error!
```

No idea why bash is mentioned there, fish is the default shell on my machine. Maybe it is a fundle problem, feel free to close if so.

**Comment by edc** [comment]
This is expected :) You need to run `bass` with a bash command. For example, `bass echo hello!`, or `bass export X=1`.

(I just pushed a [new commit](https://github.com/edc/bass/commit/cee10d460afa750209548f84766a2cdd33d9323d) so a usage message is displayed instead the error you noticed.)
