### ISSUE TITLE
fisher: I couldn't find `bass` in the index.

### ISSUE THREAD

**Issue by kWhittington** [edc/bass#27]
Hey guys,

I'm using `fish shell` w/`fisherman`. When I attempted to follow the instructions on your `README.md`, I ran into an error:

```fish
» fisher install bass
fisher: I couldn't find 'bass' in the index
No plugins were installed
```

Any idea why `fisherman` might not be able to see `bass`?

**Comment by bucaran** [comment]
@kWhittington In order for fisherman to know about bass, it must download a copy of the index first. How did you install fisherman?

If you used the curl | fish installer then this error is very strange, if you used the manual method, then I can see why you're getting the error, since the index hasn't been downloaded.

**Comment by bucaran** [comment]
Hi @kWhittington, there was a **major** version bump recently. 

Please upgrade to 2.0 (fisherman).

The following script will fix you up quickly (from scratch):

```
curl -L git.io/fisher-up-me | fish
```

If you are unsure about that, please check out the README for other instructions.

When you're done with that you should be able to install `bass` as usual.

**Comment by kWhittington** [comment]
Thx. I upgraded and temporarily had my configuration disabled (because of the `.config/fisherman` copying to `fisherman-you-can-delete-me`). Do you suggest only keeping configuration (e.g. `conf.d`, `functions`, etc.) within `.config/fish/` and not `.config/fisherman/`?

Anyway, upgraded and still had a slight hiccup installing `bass`:
```fish
» fisher install bass
INFO Installing 1 plugin/s
ARGH Fetching bass → github.com/fisherman/bass
ARGH There was an error cloning bass or more plugin/s.
INFO Try using a namespace before the plugin name: omf/bass
kwhittin at Kyles-MacBook-Pro in ~/.config
» fisher install edc/bass
INFO Installing 1 plugin/s
OKAY Fetching bass → github.com/edc/bass
OKAY Done in 975ms
```

I was thrown off at first by the `Try using a namespace before the plugin name: omf/bass`. I thought it was telling me to use `omf/bass` but after that error'd, searching on GitHub gave me the right repo.

Thx for the help.

**Comment by bucaran** [comment]
> Do you suggest only keeping configuration (e.g. conf.d, functions, etc.) within .config/fish/ and not .config/fisherman/?

Yep. Your fisherman config ~/.config/fisherman should only list installed plugins and your fish config should be the usual one that comes out of the box with fish.

Ah, yes we are not using an index anymore, so need to prepend the full namespace to the plugin.

I suggested @edc to join the fisherman org here https://github.com/edc/bass/issues/29 for discoverability, but no luck haha. It's cool. Let me know if you have any other problems.

@edc I think you can close this.
