### ISSUE TITLE
Would you like to move into the fisherman organization?

### ISSUE THREAD

**Issue by bucaran** [edc/bass#29]
Hi @edc.

fisherman just turn 2.0 and a lot of things changed, namely, we don't depend on an index anymore. In order to improve discoverability I am trying to reach out to some of the many plugin authors and ask them whether they would like to join the fisherman org and bring their plugins / themes with them.

If you enter the org, you will still be the only admin of your project, what changes is that fish-shellers browsing fisherman org will be able to find out about bass more easily.

**Comment by edc** [comment]
@bucaran That sounds good to me!

**Comment by bucaran** [comment]
Awesome! Invited. You should be able to transfer the repo now.

**Comment by edc** [comment]
I did not realize I have to transfer the ownership change the URL. Is that necessary?

**Comment by bucaran** [comment]
To help discoverability. That's the goal of all this.

You don't have to give up your ownership. You will always be both the **owner** and **admin** of your repo. If you transfer the repo to the org the only thing that will change is the URL.

If you are uncomfortable with that for some reason, then nevermind :)

fisherman will continue to support this plugin and others.

**Comment by edc** [comment]
🆒 I will think about it
