### ISSUE TITLE
Replacing colons with whitespace causes issues

### ISSUE THREAD

**Issue by paulriddle** [edc/bass#3]
I just installed nvm. When I start a new fish session `$NVM_NODEJS_ORG_MIRROR` is not set. If I run `nvm ls-remote` it works as you would expect. But during execution `$NVM_NODEJS_ORG_MIRROR` gets set to `https //nodejs.org/dist`, because bass replaces `:` with whitespace, which breaks things.

Is there a way to assign a colon-separated string to a variable? If we do `bass export foo="foo:bar"` then `foo` becomes a list of two items, but I expect to get a string. I'm kind of new to fish and never bothered to learn bash, but I figured we are replacing colons with whitespace, so that we can properly convert `$PATH`, right? Could we do it only for `$PATH` and leave all other colons alone?

**Comment by externl** [comment]
Also having this issue.

**Comment by edc** [comment]
Sorry for the late response. Github emails went to spam for some reason.

This issue has been fixed now. Let me know if you still have trouble with it.
