### ISSUE TITLE
fisher install bass

### ISSUE THREAD

**Issue by therealmarv** [edc/bass#30]
Do I do something wrong? I want to install bass with this command:

```
fisher i bass
```

but it tries to fetch from a 404 repo http://github.com/fisherman/bass . Here is the output (ignore my set warnings there):
```
 ~  fisher i bass                                                                        6.3s  Sa 23 Apr 18:44:59 2016
INFO Installing 1 plugin/s
set: Warning: universal scope selected, but a global variable 'LSCOLORS' exists.
set: Warning: universal scope selected, but a global variable 'CLICOLOR' exists.
set: Warning: universal scope selected, but a global variable 'TERM' exists.
Warning! PATH is not properly set up, '/Users/marvin/.rvm/gems/ruby-2.2.1/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.1'.
ARGH Fetching bass → github.com/fisherman/bass
ARGH There was an error cloning bass or more plugin/s.
INFO Try using a namespace before the plugin name: omf/bass
```

Or is the [bass readme](https://github.com/edc/bass#using-fisherman) outdated with the command `fisher install bass` ?

**Comment by bucaran** [comment]
@therealmarv There was a major version bump recently. Please upgrade to 2.0 (fisherman).

`curl -L git.io/fisher-up-me | fish`

**Comment by therealmarv** [comment]
ok, I applied that command you mentioned. Got the same error. :(
BTW my fish shell is brand new (just installed today) and fisherman too.

fish -v:
```
fish, version 2.2.0-790-gf28a1c5
```

fisher --version:
```
fisherman version 2.1.4 ~/.config/fish/functions/fisher.fish
```

**Comment by bucaran** [comment]
Please run

```
fisher edc/bass
```

**Comment by therealmarv** [comment]
That works! So the documentation here is wrong ;)
https://github.com/edc/bass#using-fisherman

**Comment by bucaran** [comment]
I'll PR right away.

Here is my outupt by the way.

<img width="621" alt="screen shot 2016-04-24 at 2 01 52 am" src="https://cloud.githubusercontent.com/assets/8317250/14762877/883035a6-09c0-11e6-96c6-0e31256d7c70.png">

@therealmarv One more thing, make sure to read faq#1.
https://github.com/fisherman/fisherman#1-what-is-the-required-fish-version

**Comment by therealmarv** [comment]
@bucaran thanks for mentioning. I've upgraded to head of fish (funny somehow 😄) with homebrew. It seems to work everything including brass.

**Comment by bucaran** [comment]
Sweet! Can close then :)
