### ISSUE TITLE
Last merge broke nvm execution with arguments

### ISSUE THREAD

**Issue by cacarrara** [edc/bass#34]
I couldn't find the reason, but running the last version of Bass (3e4c13c) isn't possible to pass arguments to nvm execution. The output says that `Bass encountered an error!` with `exit status: 3`.

I've checked out to previous commit (cba21b3) and everything back to work successfully.

**Comment by edc** [comment]
Can you provide an example? Also, I pushed a few minor fixes that may make a difference here. Please give it a shot.

**Comment by andersonba** [comment]
```
~ ♦ nvm ls
exit code: 3
Bass encountered an error!
```

**Comment by edc** [comment]
@andersonba. I got 
```
$ bass source ~/.nvm/nvm.sh --no-use ';' ls
README
```

Did you pull the latest version?

**Comment by tinchoz49** [comment]
Hi guys, i'm using the last version and `bass source ~/.nvm/nvm.sh --no-use ';' nvm ls` works fine but i get the same error that you are saying @andersonba when i run:`bass source ~/.nvm/nvm.sh  --no-use ';' nvm -v`

```                                                   
Node Version Manager

Note: <version> refers to any version-like string nvm understands. This includes:
  - full or partial version numbers, starting with an optional "v" (0.10, v0.1.2, v1)
  - default (built-in) aliases: node, stable, unstable, iojs, system
  - custom aliases you define with `nvm alias foo`

Usage:
  nvm --help                                Show this message
  nvm --version                             Print out the latest released version of nvm
  nvm install [-s] <version>                Download and install a <version>, [-s] from source. Uses .nvmrc if available
    --reinstall-packages-from=<version>     When installing, reinstall packages installed in <node|iojs|node version number>
    --lts                                   When installing, only select from LTS (long-term support) versions
    --lts=<LTS name>                        When installing, only select from versions for a specific LTS line
  nvm uninstall <version>                   Uninstall a version
  nvm uninstall --lts                       Uninstall using automatic LTS (long-term support) alias `lts/*`, if available.
  nvm uninstall --lts=<LTS name>            Uninstall using automatic alias for provided LTS line, if available.
  nvm use [--silent] <version>              Modify PATH to use <version>. Uses .nvmrc if available
    --lts                                   Uses automatic LTS (long-term support) alias `lts/*`, if available.
    --lts=<LTS name>                        Uses automatic alias for provided LTS line, if available.
  nvm exec [--silent] <version> [<command>] Run <command> on <version>. Uses .nvmrc if available
    --lts                                   Uses automatic LTS (long-term support) alias `lts/*`, if available.
    --lts=<LTS name>                        Uses automatic alias for provided LTS line, if available.
  nvm run [--silent] <version> [<args>]     Run `node` on <version> with <args> as arguments. Uses .nvmrc if available
    --lts                                   Uses automatic LTS (long-term support) alias `lts/*`, if available.
    --lts=<LTS name>                        Uses automatic alias for provided LTS line, if available.
  nvm current                               Display currently activated version
  nvm ls                                    List installed versions
  nvm ls <version>                          List versions matching a given <version>
  nvm ls-remote                             List remote versions available for install
    --lts                                   When listing, only show LTS (long-term support) versions
  nvm ls-remote <version>                   List remote versions available for install, matching a given <version>
    --lts                                   When listing, only show LTS (long-term support) versions
    --lts=<LTS name>                        When listing, only show versions for a specific LTS line
  nvm version <version>                     Resolve the given description to a single local version
  nvm version-remote <version>              Resolve the given description to a single remote version
    --lts                                   When listing, only select from LTS (long-term support) versions
    --lts=<LTS name>                        When listing, only select from versions for a specific LTS line
  nvm deactivate                            Undo effects of `nvm` on current shell
  nvm alias [<pattern>]                     Show all aliases beginning with <pattern>
  nvm alias <name> <version>                Set an alias named <name> pointing to <version>
  nvm unalias <name>                        Deletes the alias named <name>
  nvm reinstall-packages <version>          Reinstall global `npm` packages contained in <version> to current version
  nvm unload                                Unload `nvm` from shell
  nvm which [<version>]                     Display path to installed node version. Uses .nvmrc if available

Example:
  nvm install v0.10.32                  Install a specific version number
  nvm use 0.10                          Use the latest available 0.10.x release
  nvm run 0.10.32 app.js                Run app.js using node v0.10.32
  nvm exec 0.10.32 node app.js          Run `node app.js` with the PATH pointing to node v0.10.32
  nvm alias default 0.10.32             Set default node version on a shell

Note:
  to remove, delete, or uninstall nvm - just remove the `$NVM_DIR` folder (usually `~/.nvm`)

exit code: 127
Bass encountered an error!

```

**Comment by edc** [comment]
@tinchoz49 I don't think that is a real error. It is nvm itself reporting an error when there is actually no error. It does affect normal usage.

**Comment by worp1900** [comment]
As I am encountering this error as well I'll reopen this. How can we confirm that it's nvm throwing the error?

Executing nvm through bass on fish gives me the same as the OPs experienced:

    $ ≻ bass source ~/.nvm/nvm.sh --no-use ';' nvm -v

    Node Version Manager

    Note: <version> refers to any version-like string nvm understands. This includes:
      - full or partial version numbers, starting with an optional "v" (0.10, v0.1.2, v1)
      - default (built-in) aliases: node, stable, unstable, iojs, system
      - custom aliases you define with `nvm alias foo`

     Any options that produce colorized output should respect the `--no-colors` option.

    Usage:
      nvm --help                                Show this message
      nvm --version                             Print out the latest released version of nvm
      nvm install [-s] <version>                Download and install a <version>, [-s] from source. Uses .nvmrc if available
        --reinstall-packages-from=<version>     When installing, reinstall packages installed in <node|iojs|node version number>
        --lts                                   When installing, only select from LTS (long-term support) versions
        --lts=<LTS name>                        When installing, only select from versions for a specific LTS line
      nvm uninstall <version>                   Uninstall a version
      nvm uninstall --lts                       Uninstall using automatic LTS (long-term support) alias `lts/*`, if available.
      nvm uninstall --lts=<LTS name>            Uninstall using automatic alias for provided LTS line, if available.
      nvm use [--silent] <version>              Modify PATH to use <version>. Uses .nvmrc if available
        --lts                                   Uses automatic LTS (long-term support) alias `lts/*`, if available.
        --lts=<LTS name>                        Uses automatic alias for provided LTS line, if available.
      nvm exec [--silent] <version> [<command>] Run <command> on <version>. Uses .nvmrc if available
    
    [...]
    
    Note:
      to remove, delete, or uninstall nvm - just remove the `$NVM_DIR` folder (usually `~/.nvm`)

    exit code: 127
    Bass encountered an error!

and

    ≻ bass source ~/.nvm/nvm.sh --no-use ';' nvm ls
    exit code: 3
    Bass encountered an error!

While nvm from bash works fine:

    bash-3.2$ nvm ls
                N/A
    node -> stable (-> N/A) (default)
    iojs -> N/A (default)

So what could the error be that nvm throws while using bass but doesn't throw when called natively through bash?

**Comment by d0x** [comment]
@edc can u explain why the exit code is printed instead of returning it transparently? Or maybe adding an option like `--propagate-exit-code`. That would help for script like `nvm` were the exit code doesn't matter.

**Comment by edc** [comment]
@d0x I just pushed a commit (1e534b9) that propagates exit code if there is an error

**Comment by d0x** [comment]
Thats cool, thanks a lot!
