### ISSUE TITLE
Support for sdkman

### ISSUE THREAD

**Issue by rocketraman** [edc/bass#39]
sdman is a virtualenv-like utility for the java ecosystem: http://sdkman.io/ (source: https://github.com/sdkman/sdkman-cli)

Currently, bass grabs the environment variables after running `sdkman-init.sh`, but does not setup the `sdk` command itself. I'm not sure what that is -- perhaps it has something to do with the nested `source` calls?

**Comment by edc** [comment]
This is the same as many other tools such as nvm. The trick is to call `sdk` also with bass. See the readme section on nvm for an example.
