### ISSUE TITLE
Dollar sign on command output interrupts execution

### ISSUE THREAD

**Issue by Markcial** [edc/bass#44]
From https://github.com/sdkman/sdkman-cli/issues/294#issuecomment-300814204

Replacing line 50 of `__bass.py` with the following content fixes this issue:

    script_lines.append("printf %s;printf '\\n'" % json.dumps(line.replace('$', '\$')))

but i don't know if there is more implications

**Comment by edc** [comment]
@Markcial can you try doing it on line 75 just to be more conservative? If it works, would you mind sending a pull request?

**Comment by edc** [comment]
Correction: i meant line 72

**Comment by Markcial** [comment]
Sorry, been busy lately, let me do the PR so you can check it, thanks

**Comment by edc** [comment]
Fixed in #45 by @Markcial
