### ISSUE TITLE
Expected a combining operator like '-a' at index 1

### ISSUE THREAD

**Issue by marcosfede** [edc/bass#64]
sourcing a file with `bass source file` throws
`test: Expected a combining operator like '-a' at index 1`

fish version: 2.7.1

**Comment by edc** [comment]
Without knowing the content of `file`, or at least the portion of it that contains the `-a` part, I cannot debug.

**Comment by marcosfede** [comment]
Sorry I should have been more clear. 
It happens with any file I source
`touch test`
`bass source test`
triggers the error message

I'm on Mint 19 (does not happen on my mac machine with the same version of fish)

**Comment by edc** [comment]
This is fixed. Thanks for reporting!
