### ISSUE TITLE
Homebrew formula.

### ISSUE THREAD

**Issue by natecox** [edc/bass#7]
I'd love to see this package on homebrew for OSX; is there any interest in writing up a formula?

**Comment by externl** [comment]
I suspect a formula for this would not be approved. Homebrew requires a certain popularity rating.

**Comment by natecox** [comment]
I've never published to homebrew before, so I'm not sure what the process is, but isn't that covered by casks?

**Comment by externl** [comment]
No, casks are more for graphical applications.

**Comment by edc** [comment]
I feel this package is simple enough it does not justify the use of home-brew. Maybe we could add a simple installer script so one can just install via curl-piped-to-shell, like

    curl https://raw.githubusercontent.com/edc/bass/master/installer.sh | sh

**Comment by natecox** [comment]
@edc the shell script would be a good option and is fairly commonly used, providing you're not planning on updating the functionality in the future. I know I hate missing updates because I simply don't know about them.

**Comment by externl** [comment]
@natecox You should look at https://github.com/fish-shell/oh-my-fish. Not sure if they have bass, but I suspect they'd be more than willing to add it.

**Comment by derekstavis** [comment]
Oh My Fish is now on https://github.com/oh-my-fish/oh-my-fish @externl and @natecox. We have [foreign-env](https://github.com/oh-my-fish/plugin-foreign-env) plugin, which should work exactly like `bass`, but it's written in plain fish.

**Comment by bucaran** [comment]
@externl @natecox 

No need to reinvent the wheel. If you want to use `bass`, which I recommend, just use follow the recommended instructions in the README.

If you are a plugin-minded person, either the simple [`fundle`](https://github.com/tuvistavie/fundle) or [Fisherman](http://fisherman.sh) let you use bass.

```
fisher install bass
```
