### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by dongwangdw** [edc/bass#72]
I got python3 installed by default but python. when to run bass, it broke. Does it support python3? Or should I fix it.

**Comment by edc** [comment]
It should work. If it does not, please post the error message. Thanks!

**Comment by dongwangdw** [comment]
python means python2. what if I did not install python2 but have python3 installed? The program will complain with error. No python found. Yes, I can make a link from python3 to python. but that is not elegant.

**Comment by edc** [comment]
I think it just needs to be able to find python2 or python3 in PATH. `set -gx PATH /path/to/dir/containing/python $PATH`.

**Comment by dongwangdw** [comment]
yes. But it will be better make it invisible to python2 or python3. Just make it as `python` in the script.  As long as the python script is compatible between python2 and python3.

**Comment by edc** [comment]
It supports both python2 and python3, and I believe the travis CI tests for all major python versions.

**Comment by Talent30** [comment]
> 它应该工作。如果没有，请发布错误消息。谢谢！

This is the error message from Ubuntu 19.10
```
> command 'python' not found, but can be installed with:

sudo apt install python3         # version 3.7.5-1, or
sudo apt install python          # version 2.7.17-1
sudo apt install python-minimal  # version 2.7.17-1

You also have python3 installed, you can run 'python3' instead.

~/.local/share/omf/pkg/bass/functions/bass.fish (line 10): 
  python (dirname (status -f))/__bass.py $bash_args 3>$script_file
  ^
in function “bass”
	called on standard input
```
