### ISSUE TITLE
bass command triggers rm to remove a temp file

### ISSUE THREAD

**Issue by ricardomatias** [edc/bass#76]
OS: Mac OS X 10.14.6
Fish: 3.0.2

Every time I use `bass` I get a prompt from `rm` asking if I want to remove a temporary file. (as the example below)
This might be related to the pull requested merged yesterday, since the timing fits.

```sh
Usage: bass [-d] <bash-command>
rm: remove regular file '/var/folders/s4/ffqt6x516015rf37_gl41sqm0000gn/T/tmp.S6J9IeznGP'?
```

**Comment by edc** [comment]
I am not able to reproduce it. Could you try running it with `-d` and see if it's helpful? You may also take a look at the content of temp file and see it's indeed generated by bass.

**Comment by edc** [comment]
I think it's because your `rm` is an alias to `rm -i`. Let me push a potential fix.

**Comment by edc** [comment]
Done. Please try the fix.

**Comment by ricardomatias** [comment]
Works, thanks!
