### ISSUE TITLE
"Variables may not be used as commands"

### ISSUE THREAD

**Issue by akashkw** [edc/bass#81]
The latest merge (65cb4cbdba563b04b58eb7d4ca331cd331edd868) causes bass to break on my machine. Reverting to (20837aa45a7dee98da46ce05eaf6b7c4d7aa09a5) seems to fix the issue. I'm running Ubuntu 18.04 with fish 2.7.1. Running bass results in the error "Variables may not be used as commands, In fish, please define a function or use 'eval $python'.".
![image](https://user-images.githubusercontent.com/10525479/73971899-648e9d00-48e5-11ea-816f-848c65439693.png)

**Comment by edc** [comment]
@akashkw Could you give my fix a try? Thanks!

**Comment by akashkw** [comment]
@edc works perfectly, thank you
