### ISSUE TITLE
variables cannot be bracketed

### ISSUE THREAD

**Issue by tycho01** [edc/bass#82]
Trying bass with a syntax construct I knew differed between `bash` and `fish`:
```bash
$ bass echo ${PATH}
fish: Variables cannot be bracketed. In fish, please use {$PATH}.
bass echo ${PATH}
           ^
```
I guess this is out-of-scope for now huh :sweat_smile:, or is this just a limitation of how you're working from within fish?

**Comment by edc** [comment]
You can quote it so fish will not try to interpret the variable.

    $ bass echo '${PATH}'
