### ISSUE TITLE
Test scripts: using double `dirname` does not work if command line is `./test_dollar_on_output.fish`

### ISSUE THREAD

**Issue by RuijieYu** [edc/bass#90]
I was trying to make an unofficial package for archlinux, and noticed that the test script `test_dollar_on_output.fish` does not work if the testing was run using `cd bass/test; fish test_dollar_on_output.fish`, and fish tries to source the file `./bass.fish` which does not exist in the `test` directory. What you have in `test_bass.fish` works fine, so you can copy over what you have in that file to source the `bass.fish` file.

**Comment by edc** [comment]
Done. Thanks!
